#!/bin/bash

cookie=cookie.txt
api=http://my.nrao.edu/nrao-2.0/secure/QueryFilter.htm

# Fail on any command failure.
set -e

function get_cookie () {
    echo creating a new $cookie
    echo logging as $USER
    echo when prompted, provide your password for $api
    echo
    echo
    echo
    nraouserdb-query -L $api -c $cookie -u $USER -A $USER > /dev/null
    sed 's/TRUE\t\t/TRUE\t0\t/g' $cookie > ${cookie/.txt/.tmp}
    mv ${cookie/.txt/.tmp} $cookie
}

if ( ! ls $cookie >/dev/null 2>&1 ); then
    echo no $cookie found
    get_cookie
else
    if [ -n "`find cookie.txt -mmin +60`" ]; then
        echo $cookie is over 1 hour old, removing it
        rm $cookie
        get_cookie
    fi
fi

